### ISSUE TITLE
Installation tutorials update for Noetic release

### ISSUE THREAD

**Issue by mabelzhang** [Field-Robotics-Lab/dave#119]
Looking for feedback for a few things I noticed about the installation tutorial while testing on Noetic.

I can update the tutorials once I get a green light. Just wanted to double-check these things aren’t already somewhere that I didn’t know about, since I’m still kind of new to the repo.

- [x] #124

- [x] #125

- [x] #126

- [x] #127

I'm not done testing yet. There might be more, but I wanted to start the ticket in the interest of release timeline.

**Comment by mabelzhang** [comment]
@bsb808 tagging in case you haven't seen

**Comment by bsb808** [comment]
@mabelzhang - I'm playing catchup.  I'll work on this today and convert the tasks to issues with assignments.  Great suggestions!

**Comment by M1chaelM** [comment]
@mabelzhang Just adding a note here that I was tasked with updating the installation instructions for the host-based and docker install. Currently these pages are in disarray, as you've noticed, but I should have new versions up soon. I think this will take care of your first two items.

**Comment by M1chaelM** [comment]
Another note: if we are switching to VCS tool, this substantially changes the installation tutorials. To streamline a bit, can we resolve issue #115 before finalizing installation tutorials?

**Comment by bsb808** [comment]
> Another note: if we are switching to VCS tool, this substantially changes the installation tutorials. To streamline a bit, can we resolve issue #115 before finalizing installation tutorials?

Yes - I will do so.

**Comment by bsb808** [comment]
I converted all of these to individual issues with assignments.  I believe this links the issues so that we can divide and conquer.  If necessary, will close when the linked issues are addressed.

**Comment by bsb808** [comment]
Closing b/c all the sub-issues (bullet points) have been successfully addressed.
