### ISSUE TITLE
Rocker versioning

### ISSUE THREAD

**Issue by bsb808** [Field-Robotics-Lab/dave#124]
Rocker’s most recent release, 0.2.3, is from Nov 2020. If we install via `apt` like the DAVE Noetic wiki says, the newer features like `--volume` aren’t available. I had problems using it because it only mounts `/home`, but none of my code is in my home directory (all my stuff is in a separate partition which I usually mount with `docker run --volume`). We might want to either ask Tully to make a new release, or put a note in the DAVE wiki saying if they want new features, then they need to install Rocker following the `venv` instructions on the Rocker page (that gets the latest version, and it worked for me).

**Comment by bsb808** [comment]
I recommend we leave the default install for rocker to be the apt package - then add a footnote for those that need special features in source (e.g., `--volume`) that they use the latest from source.

**Comment by bsb808** [comment]
Will take care of this in documentation (wiki).

**Comment by M1chaelM** [comment]
This is now documented in the dockwater wiki: https://github.com/Field-Robotics-Lab/dockwater/wiki/Install-Dependencies, which is linked from the Dave wiki in the Docker installation tutorial.
