### ISSUE TITLE
Make README just point to wiki

### ISSUE THREAD

**Issue by bsb808** [Field-Robotics-Lab/dave#126]
From @mabelzhang 
Is the top-level README intentionally vague? The Wiki has a wealth of information, but it’s not discoverable. I propose putting a sentence in the top-level README that links to the wiki. #126

**Comment by bsb808** [comment]
@mabelzhang Once we get the v3.1 reorganization done - please make a tiny PR to make this so.

**Comment by mabelzhang** [comment]
Closing on #131
