### ISSUE TITLE
Move manipulation tutorials' images to wiki

### ISSUE THREAD

**Issue by mabelzhang** [Field-Robotics-Lab/dave#138]
(Post-4.0.0 release okay.)

There seem to be inconsistent locations where tutorials have their images.

The manipulation tutorials have their images in the directory `tutorial_pictures` in the repo (or `extras/tutorial_pictures` in `v3.1_reorganization` branch, to be merged into `master` for 4.0.0 release). All the images in that directory are for the manipulation tutorials only.

Looking at other tutorials in the wiki, they have images directly uploaded to the wiki, with URLs prefixed with `https://raw.githubusercontent.com/wiki/Field-Robotics-Lab/dave`
(Although, there is also ambiguity in the directories in the wiki repo - `images/`, `pictures/`, `screenshots/`, `tutorials/images/`. They should probably either be combined or categorized by tutorial.)

For consistency and easier maintenance, it's probably good to move the images in `extras/tutorial_pictures` to the wiki. That way we don't need to maintain that directory in the main repo.

(Some manipulation tutorials have images associated with a user account, with URLs that look like `https://user-images.githubusercontent.com/13877149/91655629-f0356a00-ea7f-11ea-8cea-3feccb30f19f.png`. I'm not sure whether those should be moved since they're probably associated with the author.)

The 5 manipulation tutorials referenced above:
https://github.com/Field-Robotics-Lab/dave/wiki/Swapping-out-the-Oberon7-arm-with-another-manipulator
https://github.com/Field-Robotics-Lab/dave/wiki/Electrical-Plug-Mating-Plugin
https://github.com/Field-Robotics-Lab/dave/wiki/BOP-Panel-Manipulation-Mission
https://github.com/Field-Robotics-Lab/dave/wiki/Manipulator-Force-Feedback
https://github.com/Field-Robotics-Lab/dave/wiki/Teleop-Bar-Retrieval

**Comment by bsb808** [comment]
Concur - post 4.0.0

**Comment by bsb808** [comment]
Mabel will assign sections of repos.  Move all images to wiki repo.

**Comment by mabelzhang** [comment]
Move to `images/` in wiki repo:

* [ ] `tutorial_pictures` in source code repo (10), `screenshots_fls_v1` (3), `screenshots_sonar_v2` (11) @mabelzhang
* [ ] `tutorials/images` (24) @dtdavi1 
* [ ] `screenshots` (19), `pictures` (1) @j-herman

(I'm taking this off @M1chaelM's plate since he's relieving me of chief warrior duty.)

Images in user spaces:
From `$ grep -rI "user-images.githubusercontent"`, there are 36 images across 8 wiki pages. It might be easiest if we each do the tutorials we reviewed for 4.0.0 release?
* [ ] I can take care of the ones in `Manipulator-Models.md` (1), `Electrical-Plug-Mating-Plugin.md` (4), `Swapping-out-the-Oberon7-arm-with-another-manipulator.md` (1) @mabelzhang 
* [ ] `Ocean_current_draft.md` (1), `Ocean-Current.md` (5) @j-herman do you want to do those?
* [ ] `Multibeam-Forward-Looking-Sonar.md` (21), `Install-on-Windows-using-WSL2.md` (2), `Bathymetry-Integration.md` (1) @woensug-choi do you want to do those?

Thanks everyone!

**Comment by woensug-choi** [comment]
I've updated `Multibeam-Forward-Looking-Sonar.md`, `Install-on-Windows-using-WSL2.md`, `Bathymetry-Integration.md` on wiki repo and pushed them :) All images used in those documents are now in `images` directory.

**Comment by mabelzhang** [comment]
Closing as all items in check list are completed. Thank you everyone!
