### ISSUE TITLE
dave_demo.launch issues on noetic/clang/catkin build

### ISSUE THREAD

**Issue by mlanighan** [Field-Robotics-Lab/dave#153]
We encountered a few errors with the dave_demo.launch when building the dave simulator with clang and catkin build in noetic. 
We were able to track down the issues and have submitted PRs that fix them:

1. https://github.com/Field-Robotics-Lab/uuv_simulator/pull/3
2. https://github.com/Field-Robotics-Lab/uuv_manipulators/pull/5 

The first PR adds missing function returns and fixes a non-stop warning from tf that a gazebo plugin is emitting. The second fixes a python import issue and updates a package.xml for noetic.

**Comment by woensug-choi** [comment]
I confirmed that the first PR fixes the tf for dave launch cases too.

**Comment by mlanighan** [comment]
@woensug-choi does that mean that https://github.com/Field-Robotics-Lab/uuv_simulator/pull/3 resolves https://github.com/Field-Robotics-Lab/dave/issues/152 ? 

Please let me know if I am blocking the above PRs from moving forward.

**Comment by woensug-choi** [comment]
@mlanighan Yes, I did resolve the first issue. 

It seems, not tested, that the https://github.com/ros/robot_state_publisher/pull/139 will resolve the issue too. This seems to be a more generic solution while I thought your first PR is a pretty generic solution too. Not fully sure about any possibility of breaking anything by your fix. If you can, can you test https://github.com/ros/robot_state_publisher/pull/139 ? It will be probably included in the noetic sometime soon.

**Comment by mlanighan** [comment]
I do suggest using this fix/PR branch (https://github.com/ros/robot_state_publisher/pull/139) to resolve some headaches with tf in noetic. We have been using it rather successfully without issue in various projects and can confirm it does not impact the proposed fix. We have been waiting for that fix to be merged for some time, hopefully it is pulled in soon.

However, the PR   (https://github.com/Field-Robotics-Lab/uuv_simulator/pull/3) resolves a different issue with TF in noetic (https://github.com/ros/geometry2/issues/467). I needed both fixes for the repeated warnings to disappear when running the dave_demo.

**Comment by mabelzhang** [comment]
The tf_prefix is a separate issue from #152. DAVE already worked around tf_prefix by stripping them.
As far as tf_prefix goes, https://github.com/ros/robot_state_publisher/pull/169 is the official reimplementation.

The TF_REPEATED_DATA warnings in #152 are a separate issue.
