### ISSUE TITLE
DVL gradient estimation examples still functional?

### ISSUE THREAD

**Issue by bsb808** [Field-Robotics-Lab/dave#174]
Running the demo here: https://github.com/Field-Robotics-Lab/dave/wiki/DVL-Seabed-Gradient

I do not get the same results as described in the tutorial:

1. The bathymetry seems to be missing in Gazebo, see

![image](https://user-images.githubusercontent.com/8921143/146104043-fb561f73-c701-4d80-82ed-117de26cec2d.png)

2. I don't appear to be able to use the keyboard teleop within the terminal used to run `roslaunch dave_demo_launch dave_dvl_gradient_demo_uuvsim.launch`

Note - if you are using the dockwater Docker image, you will need to add the `python3-scipy` package. See https://github.com/Field-Robotics-Lab/dockwater/pull/13

**Comment by crvogt** [comment]
@bsb808 This is in melodic?

**Comment by bsb808** [comment]
Yes - I'm fairly confident I was running with the noetic dockwater image.

**Comment by crvogt** [comment]
@bsb808 Just running it. It took several minutes for the teleop node to come up...

**Comment by bsb808** [comment]
Closing based on fix in #176
