### ISSUE TITLE
challenges with tzdata in loading the Docker image

### ISSUE THREAD

**Issue by 0-dph-0** [Field-Robotics-Lab/dave#237]
First thanks for the great work!!! Really looking forward to working with it.
Here is my data point on building the Docker image (I'm using focal building with ./build.bash noetic ). It kept getting hung up on tzdata - this seems to be a common problem in Docker (https://stackoverflow.com/questions/44331836/apt-get-install-tzdata-noninteractive)

Here was the solution that finally worked for me. 

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y tzdata

RUN unlink /etc/localtime
RUN ln -s /usr/share/zoneinfo/America/New_York /etc/localtime

Best,
dph

**Comment by mabelzhang** [comment]
Hi,

This line
```
ARG DEBIAN_FRONTEND=noninteractive
```
is something we often use, and is already in the Noetic Dockerfile in the `dockwater` repo that we recommend to use:

https://github.com/Field-Robotics-Lab/dockwater/blob/a2a046cb36689cd0fb24ff53d8fcb1f04d1d4f5c/noetic/Dockerfile#L38-L43

The unlink and setting a hardcoded time shouldn't be necessary... I've never needed that locally.

In any case, thanks for posting a solution! As the issues board is a ticket queue of problems waiting to be solved, and this ticket isn't a problem, I'm going to close it. If people run into this issue, they can search in the issues board to find this ticket. Thanks!
