### ISSUE TITLE
Hybrid glider - assembling hull and propellers

### ISSUE THREAD

**Issue by bsb808** [Field-Robotics-Lab/dave#249]
Working on #247.  Scaling the mesh files to match the physical dimensions has a side effect of not having hybrid glider propellers in correct position on vehicle.

![Screenshot from 2022-03-24 18-07-06](https://user-images.githubusercontent.com/8921143/160035248-73f8d0f4-4ea3-4bcc-bcf1-16d03b946f30.png)

Suggest addressing this by modifying the `glider_hybrid_whoi.xacro` URDF, but running out of time.

Also suggest testing that propellers still spin when commanded as expected.

**Comment by woensug-choi** [comment]
https://github.com/Field-Robotics-Lab/dave/pull/246#issuecomment-1091165583
