### ISSUE TITLE
How can i integrate Multibeam sonar and already existed Dave model? 

### ISSUE THREAD

**Issue by RounLee1** [Field-Robotics-Lab/dave#263]
I wanna intergrate Multibeam sonar, which is provided with example here https://field-robotics-lab.github.io/dave.doc/contents/dave_sensors/Multibeam-Forward-Looking-Sonar/

I noticed that there are a few code that handling multibeam sonar in sonar_snippets.xacro,  rexrov_predator.xacro
but simple action : remove annotation does not help to do it

Is there are any other special way to do it?

**Comment by woensug-choi** [comment]
You wanted to integrate it and removed it? I would recommand followg the tutorial for xacro at ros website first.
