### ISSUE TITLE
Invoking "cmake" failed while doing catkin_make

### ISSUE THREAD

**Issue by Pranav-Malpure** [Field-Robotics-Lab/dave#264]
Firstly, thank you Team DAVE, for developing this simulator. I was building the package after all the mentioned steps before and got the following error while executing the command ```catkin_make``` to build the package. This is the screenshot of the error. This is the only error and rest all steps were cleared. I would greatly appreciate if anyone could help me with this.
<img width="715" alt="Screenshot 2022-12-20 at 1 39 27 AM" src="https://user-images.githubusercontent.com/76242161/208513000-fc3c5405-7b4f-4a47-b051-f6529b09c1c4.png">

**Comment by woensug-choi** [comment]
The multibeam plugin require nvidia cuda installed on your system. It seems you dont have one. Remove nps_uw_multibeam_sonar repo in src directory and recompile
