### ISSUE TITLE
Invoking "make -j16 -l16" failed

### ISSUE THREAD

**Issue by emirsonmeez** [Field-Robotics-Lab/dave#286]
Hi! I am trying to build the package after all the mentioned steps before and got the following error while executing the command `catkin_make` to build the package. But the build process cannot be completed with the error "Invoking "make -j16 -l16" failed". Also I got some "c++: fatal error". This is the screenshot of my terminal. I would greatly appreciate if anyone could help me with this.
![Screenshot from 2024-05-24 14-16-51](https://github.com/Field-Robotics-Lab/dave/assets/134428985/330d8a7c-7842-420b-beab-e808e3d9d60a)

**Comment by woensug-choi** [comment]
Hmm not sure! But quick google search says, it's the problem with out of resource.

https://unix.stackexchange.com/questions/710460/invoking-make-j16-l16-failed
