### ISSUE TITLE
Errors and excessive verbiage on default startup

### ISSUE THREAD

**Issue by BruceMty** [Field-Robotics-Lab/dave#33]
On default startup "roslaunch uuv_dave uuv_dave.launch" I notice some errors: Couldn't open joystick force feedback and We do not have clip. I get error "Couldn't open joystick force feedback!" and an indication at the bottom that a process has died.  Also there are diagnostics verbiage that might be removed.

**Comment by M1chaelM** [comment]
Despite the exclamation point, this error is not fatal and the message is expected if you use a controller that doesn't have force-feedback capability: https://github.com/ros-drivers/joystick_drivers/issues/134

I think it's OK to leave diagnostic verbiage as-is for now unless there are specific messages you want to remove. If so, please re-open this issue.
