### ISSUE TITLE
Gliders - misaligned body frame and visual models

### ISSUE THREAD

**Issue by bsb808** [Field-Robotics-Lab/dave#47]
The body-frame for the slocum glider model is not correctly aligned.  

![Selection_079](https://user-images.githubusercontent.com/8921143/92494933-24f59f80-f1ab-11ea-86f3-d812418fb2a1.png)

The body frame should be consistent with the ROS convention from [REP 103](https://www.ros.org/reps/rep-0103.html#coordinate-frame-conventions): 
```
In relation to a body the standard is:

x forward
y left
z up
```

Can probably be done by simply rotating the visual model pose in reference to the base_link.

Need to also check the other glider models - hybrid and wave.

**Comment by M1chaelM** [comment]
It's very nice to know this standard exists. An informal survey of the models available out of the box in Gazebo suggests not too many people are following it (such that it's difficult to discern a trend). We can use this for our sensor models also.
