### ISSUE TITLE
Change stratified current message to use Vector3[] instead of separate float32[] for velocity values.

### ISSUE THREAD

**Issue by dtdavi1** [Field-Robotics-Lab/dave#84]
Using a Vector3 array instead of three float32 arrays is more in keeping with the de facto standards of the rest of the codebase.  The single velocity value generated by the same plugin is already published as a single Vector3 value.

**Comment by woensug-choi** [comment]
@dtdavi1 I remember you saying that you are working on this. If you are not, or if you need help, please let me know!

**Comment by dtdavi1** [comment]
@woensug-choi Yes, I've got it for action.  It's actually finished and committed in the branch we were working in, but I won't submit the merge request until the second issue is included.

**Comment by woensug-choi** [comment]
Thank you very much!
