### ISSUE TITLE
Predator Arm has a dismembered wrist and hand in Gazebo 11

### ISSUE THREAD

**Issue by M1chaelM** [Field-Robotics-Lab/dave#97]
Although the Predator Arm works fine in Gazebo 9, not so in Gazebo 11. See the image below and note that the wrist is floating above the arm and the hand is lying on the floor in the back of the UUV:

![broken_wrist_hand](https://user-images.githubusercontent.com/8611855/108929565-2bf95880-75f9-11eb-9e12-aa7e75ac1320.png)

Initial scan of the error messages suggests that this may be due to a name collision that Gazebo 9 forgives but Gazebo 11 gets mad about:

```
Warning [Model.cc:212] Non-unique names detected in XML children of model with name[rexrov].
Error [Model.cc:311] Joint with name [predator/wrist] in model with name [rexrov] has a name collision. Please rename this joint.
[Err] [Model.cc:123] Error Code 25 Msg: relative_to name[predator/wrist] is identical to joint name[predator/wrist], causing a graph cycle in model with name[rexrov].
[Err] [Model.cc:123] Error Code 26 Msg: PoseRelativeToGraph error, too many incoming edges at a vertex with name [predator/wrist].

```

**Comment by mabelzhang** [comment]
Ah, looks like the errors came from [FrameSemantics.cc](https://github.com/osrf/sdformat/blame/sdf9/src/FrameSemantics.cc) and were added to sdf9 a while ago in
https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/pull-requests/614/page/1
and https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/pull-requests/613/page/1

So it looks like a matter of migration to sdf9 on 20.04. Probably renaming the joint would be sufficient.
